Massive update

diff --git a/scripts/check-secrets b/scripts/check-secrets
--- a/scripts/check-secrets
+++ b/scripts/check-secrets
@@ -65,9 +65,20 @@ function get_find() {
     find . -type f -name "$pattern"
 }
 
+function check_git() {
+    local res=$(git diff --cached  $1 | grep -cE '^\+\$ANSIBLE_VAULT;')
+    return $res
+}
+
+function check_find() {
+    local res=$(grep -cE '^\$ANSIBLE_VAULT;' $1)
+    return $res
+}
+
 secrets=$(get_$query_type)
 total=0
 notencrypted=0
+notfound=0
 encrypted=0
 for i in $secrets; do
     if [ "`realpath $i`" == "`realpath $me`" ]; then
@@ -75,16 +86,25 @@ for i in $secrets; do
         continue
     fi
     total=$((total+1))
-    echo -n "$i ... "
-    if ! [ -f "$i" ] || [ $(grep -cE '^\$ANSIBLE_VAULT;' $i) -ge 1 ]; then
+    echo -n "$i -> "
+    is_secret=-1
+    if [ -f "$i" ]; then
+        check_$query_type $i
+        is_secret=$?
+        # echo -n "found $is_secret "
+    fi
+    if [ $is_secret -ge 1 ]; then
         echo -e "\e[32mENCRYPTED\e[0m"
         encrypted=$((encrypted+1))
+    elif [ $is_secret -lt 0 ]; then
+        echo -e "\e[33mNot Found\e[0m"
+        notfound=$((notfound+1))
     else
-        echo -e "\e[31mNOT ENCRYPTED\e[0m"
+        echo -e "\e[31mNot Encrypted / Commited\e[0m"
         notencrypted=$((notencrypted+1))
     fi
 done
 
-echo -e "Total: $total, \e[32mEncrypted\e[0m: $encrypted, \e[31mNot Encrypted\e[0m: $notencrypted"
+echo -e "Total: $total, \e[32mEncrypted\e[0m: $encrypted, \e[33mNot Found\e[0m $notfound, \e[31mNot Encrypted\e[0m: $notencrypted"
 
 exit $notencrypted
